DROP TABLE IF EXISTS users, categories, compilations, events, events_and_compilations, locations, requests CASCADE;

create table if not exists users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    name  VARCHAR(250) NOT NULL,

    CONSTRAINT UNIQUE_user_email UNIQUE (email),
    CONSTRAINT UNIQUE_user_name UNIQUE (name)
);

create table if not exists categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,

    CONSTRAINT UNIQUE_category_name UNIQUE (name)
);

create table if not exists compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN     NOT NULL,
    title  VARCHAR(50) NOT NULL,

    CONSTRAINT UNIQUE_title UNIQUE (title)
);

create table if not exists locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,

    CONSTRAINT UNIQUE_lat_lon UNIQUE (lat, lon)
);

create table if not exists events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation         VARCHAR(2000)               NOT NULL,
    id_category        BIGINT REFERENCES categories (id) ON DELETE CASCADE,
    created            TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description        VARCHAR(7000)               NOT NULL,
    event_date         TIMESTAMP                   NOT NULL,
    id_initiator       BIGINT REFERENCES users (id) ON DELETE CASCADE,
    location           BIGINT REFERENCES locations (id) ON DELETE CASCADE,
    paid               BOOLEAN                     NOT NULL,
    participant_limit  int                         NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE DEFAULT null,
    request_moderation BOOLEAN                     NOT NULL,
    state              VARCHAR                     NOT NULL,
    title              VARCHAR(120)                NOT NULL
);

create table if not exists events_and_compilations
(
    id_event       BIGINT REFERENCES events (id) ON DELETE CASCADE,
    id_compilation BIGINT REFERENCES compilations (id) ON DELETE CASCADE,

    primary key (id_compilation, id_event)
);

create table if not exists requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created      TIMESTAMP NOT NULL,
    id_event     BIGINT REFERENCES events (id) ON DELETE CASCADE,
    id_requester BIGINT REFERENCES users (id) ON DELETE CASCADE,
    status       VARCHAR   NOT NULL,

    CONSTRAINT UNIQUE_requester_id_for_one_event UNIQUE (id_event, id_requester)
);
